---
title: "Final Notebook"
output:
  html_document:
    toc: true
    fig_caption: true
---
#Periodic Shuffle Final Notebook

##General
We have created a game. The goal of this game was to make a children's game to allow them to practice thier skills of periodic table element identification.
We began by downloading the Unity 3D engine and Microsoft Visual Studio Code. Within Unity, we created two separate scenes using Unity's scene management system. 
The first scene was given to Emma Sampson to work on and later became the title screen. On the title screen, Emma added a background image as well as two buttons:
one button for continuing onto the next scene (the game itself) and a quit button. These both used Unity's built-in event system to call Unity fucntions. 
Specifically, the NextScene() function and the Application.Quit() function.

Within the game scene, an image game object was added and its renderer component was added to display the periodic table. Then, buttons were placed and set to 
be triggered by Laramie. 

Then, an empty gameobject with an audio source component was added to the scene by Zac. This audio component was connected to the music asset and set to loop.
Other sounds were added to this object and set to be triggered by button press events.

Lastly, a score function was added that would display the current score integer.

Future plans include adding a lives counter as well as more varied questions such as element families, element states, and element trivia. 

##Jaylin Burlin
My contributions to the game included: configuring the questions and a data array used for asking questions for each of the elements, I created a function which selected random element, I updated the question text to match the element, I created a function that selected a new element after the user picked one. 


##Emma Sampson
My contribution to the game was designing a title screen and uploading it onto unity. I also added buttons to the title screen that allowed you to begin and end the game.

##Laramie Snow
I began by setting up a scene in Unity with a periodic table background. I then made buttons overlaying each element, and all the butons were named according to their element.
When the buttons were clicked, they would darken and stay darkened until another button was pressed. I also set it up to where an event would occur upon each button press.

##Zac Young
Found and created sound effects and tracks which were implemented into the game. THese audio files were added to the assets folder and were attached to audio source on a game object within the scene.
THe audio files play constantly and loop once the title scene is bypassed. Other audio files were set up to play when events were triggered.