---
title: "Periodic Shuffle Progress Report"
output:
  html_document:
    toc: true
    fig_caption: true
---
#Periodic Shuffle Progress Report

##General
We have created a game. The goal of this game was to make a children's game to allow them to practice thier skills of periodic table element identification.

##Jaylin Burlin
My contributions to the game included: configuring the questions and a data array used for asking questions for each of the elements, I created a function which selected random element, I updated the question text to match the element, I created a function that selected a new element after the user picked one. 


##Emma Sampson
My contribution to the game was designing a title screen and uploading it onto unity. I also added buttons to the title screen that allowed you to begin and end the game.

##Laramie Snow

##Zac Young
Found and created sound effects and tracks which were implemented into the game. THese audio files were added to the assets folder and were attached to audio source on a game object within the scene.
THe audio files play constantly and loop once the title scene is bypassed. Other audio files were set up to play when events were triggered.